const screens = { landing: document.querySelector('#landingScreen'), register: document.querySelector('#registerScreen'), login: document.querySelector('#loginScreen'), app: document.querySelector('#appScreen') };
const ADMIN_EMAIL = 'adm@gmail.com';
const ADMIN_PASSWORD = 'adm 2026';
let currentUser = null;
document.querySelector('.user-badge').textContent = 'KM';
function showScreen(name) { Object.values(screens).forEach(screen => screen.classList.add('hidden')); screens[name].classList.remove('hidden'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
document.querySelectorAll('[data-screen]').forEach(button => button.addEventListener('click', () => showScreen(button.dataset.screen)));
function getAccounts() { return JSON.parse(localStorage.getItem('dojoPulseAccounts') || '[]'); }
function saveAccounts(accounts) { localStorage.setItem('dojoPulseAccounts', JSON.stringify(accounts)); }
const registerForm = document.querySelector('#registerForm');
registerForm.addEventListener('submit', event => { event.preventDefault(); const data = new FormData(registerForm); const error = document.querySelector('#registerError'); if (data.get('password') !== data.get('confirmPassword')) { error.textContent = 'As senhas precisam ser iguais.'; return; } const accounts = getAccounts(); if (accounts.some(account => account.email === data.get('email'))) { error.textContent = 'Este e-mail já está cadastrado.'; return; } accounts.push({ name: data.get('name'), email: data.get('email'), phone: data.get('phone'), document: data.get('document'), documentType: data.get('documentType'), password: data.get('password'), role: 'student', createdAt: new Date().toLocaleDateString('pt-BR') }); saveAccounts(accounts); currentUser = accounts[accounts.length - 1]; showScreen('app'); prepareUserAccess(); });
const loginForm = document.querySelector('#loginForm');
loginForm.addEventListener('submit', event => { event.preventDefault(); const data = new FormData(loginForm); const error = document.querySelector('#loginError'); if (data.get('email') === ADMIN_EMAIL && data.get('password') === ADMIN_PASSWORD) { currentUser = { name: 'Administrador', email: ADMIN_EMAIL, role: 'admin' }; showScreen('app'); prepareUserAccess(); return; } const account = getAccounts().find(item => item.email === data.get('email') && item.password === data.get('password')); if (!account) { error.textContent = 'E-mail ou senha inválidos.'; return; } currentUser = account; showScreen('app'); prepareUserAccess(); });
document.querySelector('#forgotPassword').addEventListener('click', () => { document.querySelector('#loginError').textContent = 'Digite seu e-mail para solicitar a recuperação.'; });
const panels = { classes: document.querySelector('#classesPanel'), levels: document.querySelector('#levelsPanel'), notices: document.querySelector('#noticesPanel') };
const navigation = document.querySelector('.app-sidebar nav');
const adminButton = document.createElement('button'); adminButton.className = 'admin-only'; adminButton.dataset.panel = 'admin'; adminButton.innerHTML = '▣ <span>Administração</span>'; navigation.appendChild(adminButton);
const adminPanel = document.createElement('section'); adminPanel.className = 'panel-view'; adminPanel.id = 'adminPanel'; adminPanel.innerHTML = '<p class="eyebrow"><i></i> CONTROLE RESTRITO</p><h1>Administração</h1><p class="app-subtitle">Cadastros realizados na plataforma.</p><div class="admin-summary"><b id="accountCount">0</b><span>pessoas cadastradas</span></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Nome</th><th>E-mail</th><th>Telefone</th><th>Documento</th><th>Cadastro</th></tr></thead><tbody id="accountTable"></tbody></table></div>';
document.querySelector('.app-body').appendChild(adminPanel); panels.admin = adminPanel;
function prepareUserAccess() { adminButton.classList.toggle('visible', currentUser.role === 'admin'); if (currentUser.role === 'admin') { showPanel('admin'); renderAccounts(); } else { showPanel('classes'); } }
function showPanel(name) { Object.values(panels).forEach(panel => panel.classList.remove('active')); panels[name].classList.add('active'); document.querySelectorAll('[data-panel]').forEach(button => button.classList.toggle('active', button.dataset.panel === name)); document.querySelector('#panelTitle').textContent = name === 'classes' ? 'Turmas' : name === 'levels' ? 'Graduações' : name === 'notices' ? 'Avisos' : 'Administração'; }
document.querySelectorAll('[data-panel]').forEach(button => button.addEventListener('click', () => showPanel(button.dataset.panel)));
adminButton.addEventListener('click', () => { renderAccounts(); showPanel('admin'); });
function renderAccounts() { const accounts = getAccounts(); document.querySelector('#accountCount').textContent = accounts.length; document.querySelector('#accountTable').innerHTML = accounts.length ? accounts.map(account => `<tr><td>${account.name}</td><td>${account.email}</td><td>${account.phone}</td><td>${account.documentType} ${account.document}</td><td>${account.createdAt}</td></tr>`).join('') : '<tr><td colspan="5">Nenhum cadastro realizado ainda.</td></tr>'; }
